# Generated by Django 4.2.7 on 2023-12-02 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='username',
            field=models.TextField(blank=True, default='', max_length=255),
        ),
    ]
