# Generated by Django 4.2.7 on 2023-12-02 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_login_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.DateTimeField(auto_now_add=True)),
                ('username', models.TextField(blank=True, default='', max_length=255)),
                ('password', models.TextField(blank=True, default='', max_length=255)),
            ],
        ),
    ]
