# Generated by Django 4.2.7 on 2023-12-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_signup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signup',
            options={'ordering': ['userid']},
        ),
        migrations.RemoveField(
            model_name='login',
            name='id',
        ),
        migrations.RemoveField(
            model_name='login',
            name='username',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='id',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='username',
        ),
        migrations.AddField(
            model_name='login',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='userid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='signup',
            name='userid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
