# Generated by Django 4.1.5 on 2023-12-13 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_customuser_tracker_delete_appuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='full_name',
        ),
        migrations.DeleteModel(
            name='Tracker',
        ),
    ]
