# Generated by Django 4.2.7 on 2023-12-02 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.DateTimeField(auto_now_add=True)),
                ('flightname', models.TextField(blank=True, default='', max_length=255)),
                ('destination', models.TextField(blank=True, default='', max_length=255)),
                ('price', models.TextField(blank=True, default='', max_length=255)),
                ('date', models.TextField(blank=True, default='', max_length=255)),
            ],
            options={
                'ordering': ['userid'],
            },
        ),
    ]
