# Generated by Django 4.1.5 on 2023-12-13 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='userid',
        ),
    ]
